import type { Metadata } from "next";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { AdUnit } from "@/components/AdUnit";
import { ADSENSE_SLOT_ARTICLE } from "@/lib/env";
import { SITE_URL, GITHUB_URL } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Privacy Policy — TechPulse",
  description:
    "How TechPulse handles data on the website and the Android app, including advertising cookies and third-party services.",
  alternates: { canonical: `${SITE_URL}/privacy` },
};

export default function PrivacyPage(): React.ReactElement {
  return (
    <>
      <Navbar />
      <main className="bg-white px-4 py-16 sm:px-6 lg:px-8">
        <article className="prose-custom">
          <h1>Privacy Policy</h1>
          <p className="lede">Last updated: 17 April 2026</p>

          <p>
            TechPulse (&quot;we&quot;, &quot;our&quot;) operates{" "}
            <strong>techpulse-web.vercel.app</strong> (the &quot;Site&quot;)
            and the <strong>TechPulse Android application</strong> (the
            &quot;App&quot;). This policy describes what we collect, why,
            and how to exercise your rights.
          </p>

          <h2>1. Information we collect</h2>

          <h3>1.1 Directly</h3>
          <p>
            We do not require an account. We do not ask for your name,
            email, phone number, date of birth, or payment information. No
            registration form exists anywhere on the Site or the App.
          </p>

          <h3>1.2 Automatically on the Site</h3>
          <p>
            When you visit the Site, standard server logs record your IP
            address, user agent string, and the path you requested. These
            logs are generated by our hosting provider (Vercel) and are
            retained for operational and security purposes only.
          </p>

          <h3>1.3 Automatically in the App</h3>
          <p>
            The App stores your bookmarks, theme choice, and notification
            preferences locally on your device. Bookmarks are never
            transmitted to any server. Anonymous crash reports and basic
            usage events may be sent to Firebase Crashlytics to help
            diagnose issues; these reports contain device model, OS version,
            and stack trace — no personal identifiers.
          </p>

          <h2>2. Advertising and cookies</h2>
          <p>
            The Site displays advertisements served by Google AdSense.
            AdSense and its partners may use cookies, device identifiers,
            and similar technologies to serve ads based on your prior
            visits to this and other websites, which enables personalized
            advertising.
          </p>
          <ul>
            <li>
              You can opt out of personalized advertising at{" "}
              <a
                href="https://adssettings.google.com/"
                target="_blank"
                rel="noopener noreferrer"
              >
                Google Ads Settings
              </a>
              .
            </li>
            <li>
              For details on how Google uses data from partner sites, see{" "}
              <a
                href="https://policies.google.com/technologies/partner-sites"
                target="_blank"
                rel="noopener noreferrer"
              >
                policies.google.com/technologies/partner-sites
              </a>
              .
            </li>
            <li>
              Visitors from the EEA, UK, or Switzerland see a
              Google-certified consent banner on their first visit and can
              accept, reject, or customize ad-related data processing.
              Rejection is always available as a single click.
            </li>
          </ul>

          <div className="my-10">
            <AdUnit slot={ADSENSE_SLOT_ARTICLE} />
          </div>

          <h2>3. Third parties</h2>
          <table>
            <thead>
              <tr>
                <th>Service</th>
                <th>Purpose</th>
                <th>Policy</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Vercel</td>
                <td>Hosting, CDN, server logs</td>
                <td>
                  <a
                    href="https://vercel.com/legal/privacy-policy"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    vercel.com/legal/privacy-policy
                  </a>
                </td>
              </tr>
              <tr>
                <td>Google AdSense</td>
                <td>Advertising</td>
                <td>
                  <a
                    href="https://policies.google.com/privacy"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    policies.google.com/privacy
                  </a>
                </td>
              </tr>
              <tr>
                <td>Firebase Crashlytics (App only)</td>
                <td>Crash reporting</td>
                <td>
                  <a
                    href="https://firebase.google.com/support/privacy"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    firebase.google.com/support/privacy
                  </a>
                </td>
              </tr>
              <tr>
                <td>Supabase</td>
                <td>Article metadata storage (read-only from the App)</td>
                <td>
                  <a
                    href="https://supabase.com/privacy"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    supabase.com/privacy
                  </a>
                </td>
              </tr>
            </tbody>
          </table>
          <p>We do not sell or rent personal information.</p>

          <h2>4. Your rights</h2>
          <p>
            Residents of the EEA, the UK, and California have rights to
            access, correct, delete, or object to the processing of their
            personal data. Because we collect minimal data and do not
            maintain user accounts, most requests relate to advertising
            cookies — which you can exercise directly through Google Ads
            Settings linked above. For anything else, contact us (section
            7) and we will respond within thirty days.
          </p>

          <h2>5. Children&apos;s privacy</h2>
          <p>
            The Site and the App are not directed to children under 13 (or
            the relevant age of digital consent in your jurisdiction). We
            do not knowingly collect personal information from children. If
            you believe a child has submitted data to us, contact us and we
            will delete it.
          </p>

          <h2>6. Security</h2>
          <p>
            The Site is served over HTTPS. The App communicates with
            Supabase over HTTPS. No system is perfectly secure; report
            vulnerabilities responsibly via the GitHub contact below.
          </p>

          <h2>7. Changes and contact</h2>
          <p>
            We may update this policy. Updates are effective when posted at
            this URL. Material changes will be flagged on the homepage for
            at least fourteen days.
          </p>
          <p>
            Questions or requests: open an issue at{" "}
            <a href={GITHUB_URL} target="_blank" rel="noopener noreferrer">
              github.com/muhammadafzal-dev
            </a>
            .
          </p>
        </article>
      </main>
      <Footer />
    </>
  );
}
